spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:estoque
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  devtools:
    restart:
      enabled: true
      exclude: /**,public/**
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
